"""empty message

Revision ID: 43dba6200908
Revises: b51157cbf636
Create Date: 2023-02-10 17:27:31.621219

"""
from alembic import op
import sqlalchemy as sa

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")

# revision identifiers, used by Alembic.
revision = '43dba6200908'
down_revision = 'b51157cbf636'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('direct_channels_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_one', sa.Integer(), nullable=False),
    sa.Column('user_two', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    if environment == "production":
        op.execute(f"ALTER TABLE direct_channels_table SET SCHEMA {SCHEMA};")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('direct_channels_table')
    # ### end Alembic commands ###
