from app.models import db, Channel, environment, SCHEMA


def seed_channels():
    demo_channel1 = Channel(
        name='General Gaming Discussion', description='General Gaming Chat', server_id=1 )
    demo_channel2 = Channel(
        name='Game Recommendations', description='Recommend Your Favorite Games', server_id=1 )
    demo_channel3 = Channel(name='PC Gaming', server_id=1 )
    demo_channel4 = Channel(name='Console Gaming', server_id=1 )
    demo_channel5 = Channel(name='Retro Gaming', server_id=1 )
    demo_channel6 = Channel(name='Mobile Gaming', server_id=1 )
    demo_channel7 = Channel(name='Esports News', server_id=1 )
    demo_channel8 = Channel(name='Game Reviews', server_id=1 )
    demo_channel9 = Channel(name='Streaming & Content Creation', server_id=1 )
    demo_channel10 = Channel(name='LFG (Looking for Group)', server_id=1 )
    demo_channel11 = Channel(name='Game Development & Design', server_id=1 )
    demo_channel12 = Channel(name='Mods & Custom Content', server_id=1 )
    demo_channel13 = Channel(name='Gaming Hardware & Accessories', server_id=1 )
    demo_channel14 = Channel(name='Gaming News & Events', server_id=1 )
    demo_channel15 = Channel(name='Community Events', server_id=1 )
    demo_channel16 = Channel(name='Memes & Jokes', server_id=1 )
    demo_channel17 = Channel(name='Off-Topic Chat', server_id=1 )
    db.session.add(demo_channel1)
    db.session.add(demo_channel2)
    db.session.add(demo_channel3)
    db.session.add(demo_channel4)
    db.session.add(demo_channel5)
    db.session.add(demo_channel6)
    db.session.add(demo_channel7)
    db.session.add(demo_channel8)
    db.session.add(demo_channel9)
    db.session.add(demo_channel10)
    db.session.add(demo_channel11)
    db.session.add(demo_channel12)
    db.session.add(demo_channel13)
    db.session.add(demo_channel14)
    db.session.add(demo_channel15)
    db.session.add(demo_channel16)
    db.session.add(demo_channel17)
    demo_channel18 = Channel(name='General Discussion', server_id=2 )
    demo_channel19 = Channel(name='Movies & TV Shows', server_id=2 )
    demo_channel20 = Channel(name='Music', server_id=2 )
    demo_channel21 = Channel(name='Gaming', server_id=2 )
    demo_channel22 = Channel(name='Sports', server_id=2 )
    demo_channel23 = Channel(name='Books & Literature', server_id=2 )
    demo_channel24 = Channel(name='Comedy', server_id=2 )
    demo_channel25 = Channel(name='Memes & Jokes', server_id=2 )
    demo_channel26 = Channel(name='Art & Design', server_id=2 )
    demo_channel27 = Channel(name='Virtual Events & Parties', server_id=2 )
    demo_channel28 = Channel(name='Food & Drink', server_id=2 )
    demo_channel29 = Channel(name='Travel', server_id=2 )
    demo_channel30 = Channel(name='Pop Culture', server_id=2 )
    demo_channel31 = Channel(name='Technology & Gadgets', server_id=2 )
    demo_channel32 = Channel(name='DIY & Crafts', server_id=2 )
    demo_channel33 = Channel(name='Photography', server_id=2 )
    demo_channel34 = Channel(name='Performing Arts', server_id=2 )
    demo_channel35 = Channel(name='News & Current Events', server_id=2 )
    db.session.add(demo_channel18)
    db.session.add(demo_channel19)
    db.session.add(demo_channel20)
    db.session.add(demo_channel21)
    db.session.add(demo_channel22)
    db.session.add(demo_channel23)
    db.session.add(demo_channel24)
    db.session.add(demo_channel25)
    db.session.add(demo_channel26)
    db.session.add(demo_channel27)
    db.session.add(demo_channel28)
    db.session.add(demo_channel29)
    db.session.add(demo_channel30)
    db.session.add(demo_channel31)
    db.session.add(demo_channel32)
    db.session.add(demo_channel33)
    db.session.add(demo_channel34)
    db.session.add(demo_channel35)
    demo_channel36 = Channel(name='Introductions', description='A channel for new members to introduce themselves and share their interests', server_id=3 )
    demo_channel37 = Channel(name='Artwork', description='Share your art, whether it be digital, traditional, or any other medium', server_id=3 )
    demo_channel38 = Channel(name='Writing ', description='Post your written work, including poetry, short stories, novels, etc', server_id=3 )
    demo_channel39 = Channel(name='Music', server_id=3 )
    demo_channel40 = Channel(name='Photography ', server_id=3 )
    demo_channel41 = Channel(name='Collaboration',  server_id=3 )
    demo_channel42 = Channel(name='Feedback ', server_id=3 )
    demo_channel43 = Channel(name='Events',  server_id=3 )
    demo_channel44 = Channel(name='General', server_id=3 )



    db.session.add(demo_channel36)
    db.session.add(demo_channel37)
    db.session.add(demo_channel38)
    db.session.add(demo_channel39)
    db.session.add(demo_channel40)
    db.session.add(demo_channel41)
    db.session.add(demo_channel42)
    db.session.add(demo_channel43)
    db.session.add(demo_channel44)



    demo_channel45 = Channel(name='General Fitness', description='a general channel for discussions related to fitness and health', server_id=4 )
    demo_channel46 = Channel(name='Workout Tips', description='Share workout tips, exercises, and routines', server_id=4 )
    demo_channel47 = Channel(name='Nutrition Advice', description='Discuss nutrition, healthy eating, and meal planning',server_id=4 )
    demo_channel48 = Channel(name='Progress Updates', description='Share progress updates, before and after photos, and success stories', server_id=4 )
    demo_channel49 = Channel(name='Fitness Gear', description='Discuss and review fitness gear and equipment',  server_id=4 )
    demo_channel50 = Channel(name='Yoga Pilates',  server_id=4 )
    demo_channel51 = Channel(name='Running Group',  server_id=4 )
    demo_channel52 = Channel(name='Challenges',  server_id=4 )
    demo_channel53 = Channel(name='Accountability Buddies', description='a channel for finding and connecting with accountability buddies to stay on track with fitness goals', server_id=4 )
    db.session.add(demo_channel45)
    db.session.add(demo_channel46)
    db.session.add(demo_channel47)
    db.session.add(demo_channel48)
    db.session.add(demo_channel49)
    db.session.add(demo_channel50)
    db.session.add(demo_channel51)
    db.session.add(demo_channel52)
    db.session.add(demo_channel53)
    db.session.commit()


def undo_channels():
    if environment == "production":
        db.session.execute(f"TRUNCATE table {SCHEMA}.channels_table RESTART IDENTITY CASCADE;")
    else:
        db.session.execute("DELETE FROM channels_table")

    db.session.commit()
