"""empty message

Revision ID: 1d32c4aa7327
Revises: 05fc49ae6d08
Create Date: 2023-02-16 08:00:02.364046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d32c4aa7327'
down_revision = '05fc49ae6d08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('direct_messages_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('edited', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('direct_messages_table', schema=None) as batch_op:
        batch_op.drop_column('edited')

    # ### end Alembic commands ###
