"""empty message

Revision ID: a513676c43f9
Revises: 8dffe3cc87e7
Create Date: 2023-02-11 13:18:29.882304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a513676c43f9'
down_revision = '8dffe3cc87e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('channels_table', schema=None) as batch_op:
        batch_op.drop_column('server_id')

    with op.batch_alter_table('memberships_table', schema=None) as batch_op:
        batch_op.alter_column('server_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'servers_table', ['server_id'], ['id'], ondelete='cascade')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='cascade')

    with op.batch_alter_table('servers_table', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['mod_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servers_table', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('memberships_table', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('server_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('channels_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('server_id', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###